# H2 database
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:bank;DB_CLOSE_DELAY=-1

# Schema
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Exchange API
quarkus.rest-client.exchange-api.url=https://v6.exchangerate-api.com
exchange.api.key=${EXCHANGE_API_KEY:}

# Frankfurter API
quarkus.rest-client.frankfurter-api.url=https://api.frankfurter.dev